name: Notify Updates in Group

on:
	workflow_run:
		workflows: ["Ion Publish"]

jobs:
	on-success:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: notify group about the new update
      uses: appleboy/telegram-action@master
      with:
        to: -1001456201779
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: 🎉 A new version of Ion is out.
