name: Ion Publish

on:
  release:
    types:
      - created

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          yarn install

      - name: Bootstraping Packages
        run: |
          npx lerna bootstrap

      - name: Building Packages
        run: yarn gulp
        env:
          CI: false

      - name: Publishing to NPM
        working-directory: ./packages/ion
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
  notify:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: -1001456201779
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: 🎉 New Version of Ion is up
