name: telegram message

on:
  release:
    types:
      - created

jobs:
  build:
    name: Notify Chat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send message in chat about the event
        uses: appleboy/telegram-action@master
        with:
          to: -1001456201779
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: 🚀 New version of Ion is released (**${{ github.event.release.tag_name  }}**)
          format: markdown
